/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Code.DateValidator;
import static Code.EmailValidation.validateEmail;
import static Code.FullNameValidation.validateFullName;
import static Code.MobileNumberValidation.isInteger;
import static Code.PasswordValidation.validatePassword;
import static Code.StudentIDValidation.isValidStudentId;
import static Code.UsernameValidation.validateUsername;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dayna
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     * @param uname
     */
    public Booking(String uname) {
        initComponents();
        MyApplication ma = new MyApplication(uname);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        NaviBar4 = new javax.swing.JPanel();
        Logo4 = new javax.swing.JLabel();
        Wednesday4 = new javax.swing.JLabel();
        MyApplication = new javax.swing.JLabel();
        AvailableRoom = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Wel = new javax.swing.JLabel();
        Fullname = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoomType = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        ADdd = new javax.swing.JTextField();
        ADyyyy = new javax.swing.JTextField();
        ADmm = new javax.swing.JTextField();
        CODdd = new javax.swing.JTextField();
        CODmm = new javax.swing.JTextField();
        CODyyyy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Price = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(852, 550));
        jPanel5.setLayout(null);

        NaviBar4.setBackground(new java.awt.Color(74, 31, 61));
        NaviBar4.setMinimumSize(new java.awt.Dimension(852, 80));

        Logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N
        Logo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logo4MouseClicked(evt);
            }
        });

        Wednesday4.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        Wednesday4.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday4.setText("WEDNESDAY");

        MyApplication.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        MyApplication.setForeground(new java.awt.Color(255, 255, 255));
        MyApplication.setText("My Application");
        MyApplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MyApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyApplicationMouseClicked(evt);
            }
        });

        AvailableRoom.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        AvailableRoom.setForeground(new java.awt.Color(255, 255, 255));
        AvailableRoom.setText("Available Room");
        AvailableRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvailableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableRoomMouseClicked(evt);
            }
        });

        Booking.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Booking.setForeground(new java.awt.Color(255, 255, 255));
        Booking.setText("Booking");
        Booking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Payment.setForeground(new java.awt.Color(255, 255, 255));
        Payment.setText("Payment");
        Payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NaviBar4Layout = new javax.swing.GroupLayout(NaviBar4);
        NaviBar4.setLayout(NaviBar4Layout);
        NaviBar4Layout.setHorizontalGroup(
            NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBar4Layout.createSequentialGroup()
                .addGroup(NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NaviBar4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Wednesday4))
                    .addGroup(NaviBar4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Logo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NaviBar4Layout.setVerticalGroup(
            NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBar4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        jPanel5.add(NaviBar4);
        NaviBar4.setBounds(0, 0, 852, 100);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 850, 20);

        jPanel6.setMinimumSize(new java.awt.Dimension(852, 80));

        jLabel16.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(74, 31, 61));
        jLabel16.setText(" Booking");

        Wel.setText("Welcome ,");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(Wel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Wel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 100, 852, 80);

        Fullname.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        Fullname.setForeground(new java.awt.Color(74, 31, 61));
        Fullname.setText("Full Name (as per NRIC) :");
        jPanel5.add(Fullname);
        Fullname.setBounds(130, 210, 200, 20);

        Gender.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        Gender.setForeground(new java.awt.Color(74, 31, 61));
        Gender.setText("Gender :");
        jPanel5.add(Gender);
        Gender.setBounds(130, 260, 120, 20);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 31, 61));
        jLabel1.setText("Room Type :");

        RoomType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select --", "Superior Single Room", "Twin Sharing Room" }));
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 31, 61));
        jLabel2.setText("Arrival Date :");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 31, 61));
        jLabel3.setText("Check-out date:");

        ADdd.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        ADdd.setText("dd");
        ADdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ADddFocusGained(evt);
            }
        });
        ADdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADddActionPerformed(evt);
            }
        });

        ADyyyy.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        ADyyyy.setText("yyyy");
        ADyyyy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ADyyyyFocusGained(evt);
            }
        });
        ADyyyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADyyyyActionPerformed(evt);
            }
        });

        ADmm.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        ADmm.setText("mm");
        ADmm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ADmmFocusGained(evt);
            }
        });
        ADmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADmmActionPerformed(evt);
            }
        });

        CODdd.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        CODdd.setText("dd");
        CODdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CODddFocusGained(evt);
            }
        });

        CODmm.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        CODmm.setText("mm");
        CODmm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CODmmFocusGained(evt);
            }
        });

        CODyyyy.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        CODyyyy.setText("yyyy");
        CODyyyy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CODyyyyFocusGained(evt);
            }
        });

        jLabel4.setText("/");

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel7.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ADdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADmm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(CODdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(CODmm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CODyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ADyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ADmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CODdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CODyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CODmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(130, 400, 600, 80);

        fullname.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel5.add(fullname);
        fullname.setBounds(320, 210, 160, 25);

        jButton1.setText("jButton1");
        jPanel5.add(jButton1);
        jButton1.setBounds(410, 430, 75, 23);

        jButton3.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(74, 31, 61));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(460, 500, 130, 30);

        Submit.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(74, 31, 61));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel5.add(Submit);
        Submit.setBounds(250, 500, 130, 30);

        buttonGroup1.add(Male);
        Male.setText("Male");
        jPanel5.add(Male);
        Male.setBounds(210, 260, 49, 21);

        buttonGroup1.add(Female);
        Female.setText("Female");
        jPanel5.add(Female);
        Female.setBounds(270, 260, 61, 21);

        Price.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        Price.setForeground(new java.awt.Color(74, 31, 61));
        Price.setText("Price (RM) :");
        jPanel5.add(Price);
        Price.setBounds(130, 310, 100, 20);

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(price);
        price.setBounds(230, 310, 120, 20);

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("*** In terms of conditions, application will be declined if dates entered wrongly ( Monthly basis ) ***");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(50, 370, 760, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableRoomMouseClicked
        // TODO add your handling code here:
        String uname = null;
        AvailableRoom ar = new AvailableRoom(uname);
        ar.Username.setText(Username.getText());
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_AvailableRoomMouseClicked

    private void MyApplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyApplicationMouseClicked
        // TODO add your handling code here:
        MyApplication myapp = new MyApplication(Username.getText());
        myapp.Username.setText(Username.getText());
        myapp.setVisible(true);
        dispose();
    }//GEN-LAST:event_MyApplicationMouseClicked

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String uname = null;
        AvailableRoomSearch ars = new AvailableRoomSearch(uname);
        ars.Username.setText(Username.getText());
        ars.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ADmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADmmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADmmActionPerformed

    private void ADyyyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADyyyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADyyyyActionPerformed

    private void RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeActionPerformed
        // TODO add your handling code here:
        String p = RoomType.getSelectedItem().toString();
        if(p.equals("Superior Single Room")){
            price.setText("1500");
        }else if(p.equals("Twin Sharing Room")){
            price.setText("1000");
        }else{
            price.setText("0");
        }
    }//GEN-LAST:event_RoomTypeActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String fname = fullname.getText();
//        sid.setText(Username.getText());
        String RT = RoomType.getSelectedItem().toString();
        String ADD = ADdd.getText();
        String AMM = ADmm.getText();
        String AYYYY = ADyyyy.getText();
        String CDD = CODdd.getText();
        String CMM = CODmm.getText();
        String CYYYY = CODyyyy.getText();
        String gender = null;
        
        int done = 1;
        int add = 1;
        boolean FNameisValid = validateFullName(fname);
        

        try{
            if(fname.equals("")){
                fullname.setBackground(Color.pink);
                done = 0;
                add = 0;
            }else if(!FNameisValid ){
                JOptionPane.showMessageDialog(null, "Invalid Full Name format.");
                add = 0;
            }
                      
            if(RT.equals("-- select --")){
                RoomType.setBackground(Color.pink);                
                done = 0;
                add = 0;
            }
            
            if(ADD.equals("")){
                ADdd.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(AMM.equals("")){
                ADmm.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(AYYYY.equals("")){
                ADyyyy.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(CDD.equals("")){
                CODdd.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(CMM.equals("")){
                CODmm.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(CYYYY.equals("")){
                CODyyyy.setBackground(Color.pink);
                done = 0;
                add = 0;
            }
            
            if(!Male.isSelected()&&!Female.isSelected()){
                done = 0;
                add = 0;
            }else if(Male.isSelected()){
                gender = "Male";
                add = 1;
            }else if(Female.isSelected()){
                gender = "Female";
                add=1;
            }   
            
            int maxNumber = 0;
                String line;
                try (BufferedReader reader = new BufferedReader(new FileReader("Application.txt"))) {
                     
                    while ((line = reader.readLine()) != null) {
                        String[] parts = line.split(">");
                        String storedid = parts[0];
                        String stid = parts[1];
                        String status = parts[7];
                        int number = Integer.parseInt(storedid);
                        if (number > maxNumber) {
                            maxNumber = number;
                        }
                        if(status.equals("Pending")&&stid.equals(Username.getText())){
                            add = 0;
                            JOptionPane.showMessageDialog(null,"Found pending application, new booking not available");
                        }
                    }
                 
                } catch (IOException e) {
                    System.out.println("Error reading the file: " + e.getMessage());
                    return;
                }

                int updatedNumber = maxNumber + 1;
                
            
            if(done == 0){
                JOptionPane.showMessageDialog(null, "Required field found empty.");
            }else if(add == 1){
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("Application.txt", true))){                    
                    writer.newLine();
                    writer.write(updatedNumber+">"+Username.getText()+">"+fname+">"+gender+">"+RT+">"+ADD+AMM+AYYYY+">"+CDD+CMM+CYYYY+">Pending"+">"+"Pending>"+price.getText());
                    writer.close();
                    JOptionPane.showMessageDialog(this, "Application submited");
                    
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
                }
            }    
            
            
                                          
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, "Error.");
        }

    }//GEN-LAST:event_SubmitActionPerformed

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        String username = null;
        Booking b = new Booking(username);
        b.Username.setText(Username.getText());
//        b.sid.setText(Username.getText());
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_BookingMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
        // TODO add your handling code here:
        String username = null;
        Payment payment = new Payment(username);
        payment.Username.setText(Username.getText());
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_PaymentMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                WelcomePage wp = new WelcomePage();
                wp.setVisible(true);
                dispose();
            } else {
                JOptionPane.getRootFrame().dispose();
            }
    }//GEN-LAST:event_LogoutMouseClicked

    private void Logo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logo4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Logo4MouseClicked

    private void ADddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADddActionPerformed

    private void ADddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ADddFocusGained
        // TODO add your handling code here:
        ADdd.setText("");
    }//GEN-LAST:event_ADddFocusGained

    private void ADmmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ADmmFocusGained
        // TODO add your handling code here:
        ADmm.setText("");
    }//GEN-LAST:event_ADmmFocusGained

    private void ADyyyyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ADyyyyFocusGained
        // TODO add your handling code here:
        ADyyyy.setText("");
    }//GEN-LAST:event_ADyyyyFocusGained

    private void CODddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CODddFocusGained
        // TODO add your handling code here:
        CODdd.setText("");
    }//GEN-LAST:event_CODddFocusGained

    private void CODmmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CODmmFocusGained
        // TODO add your handling code here:
        CODmm.setText("");
    }//GEN-LAST:event_CODmmFocusGained

    private void CODyyyyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CODyyyyFocusGained
        // TODO add your handling code here:
        CODyyyy.setText("");
    }//GEN-LAST:event_CODyyyyFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String uname = null;
                new Booking(uname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADdd;
    private javax.swing.JTextField ADmm;
    private javax.swing.JTextField ADyyyy;
    private javax.swing.JLabel AvailableRoom;
    private javax.swing.JLabel Booking;
    private javax.swing.JTextField CODdd;
    private javax.swing.JTextField CODmm;
    private javax.swing.JTextField CODyyyy;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Fullname;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Logo4;
    private javax.swing.JLabel Logout;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel MyApplication;
    private javax.swing.JPanel NaviBar4;
    private javax.swing.JLabel Payment;
    private javax.swing.JLabel Price;
    private javax.swing.JComboBox<String> RoomType;
    private javax.swing.JButton Submit;
    public javax.swing.JLabel Username;
    private javax.swing.JLabel Wednesday4;
    public javax.swing.JLabel Wel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables

    private boolean validateDate(String ADD, String AMM, String AYYYY) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
