/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dayna
 */
public class AvailableRoomSearch extends javax.swing.JFrame {

    /**
     * Creates new form AvailableRoomSearch
     */
    public AvailableRoomSearch(String uname) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        AvailableRoomSearch = new javax.swing.JPanel();
        NaviBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Wednesday = new javax.swing.JLabel();
        MyApplication = new javax.swing.JLabel();
        AvailableRoom = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Wel = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RoomType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BookNow = new javax.swing.JButton();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        Check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AvailableRoomSearch.setBackground(new java.awt.Color(255, 255, 255));
        AvailableRoomSearch.setPreferredSize(new java.awt.Dimension(852, 550));
        AvailableRoomSearch.setLayout(null);

        NaviBar.setBackground(new java.awt.Color(74, 31, 61));
        NaviBar.setMinimumSize(new java.awt.Dimension(852, 80));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });

        Wednesday.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        Wednesday.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday.setText("WEDNESDAY");

        MyApplication.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        MyApplication.setForeground(new java.awt.Color(255, 255, 255));
        MyApplication.setText("My Application");
        MyApplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MyApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyApplicationMouseClicked(evt);
            }
        });

        AvailableRoom.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        AvailableRoom.setForeground(new java.awt.Color(255, 255, 255));
        AvailableRoom.setText("Available Room");
        AvailableRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvailableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableRoomMouseClicked(evt);
            }
        });

        Booking.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Booking.setForeground(new java.awt.Color(255, 255, 255));
        Booking.setText("Booking");
        Booking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Payment.setForeground(new java.awt.Color(255, 255, 255));
        Payment.setText("Payment");
        Payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NaviBarLayout = new javax.swing.GroupLayout(NaviBar);
        NaviBar.setLayout(NaviBarLayout);
        NaviBarLayout.setHorizontalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Wednesday))
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NaviBarLayout.setVerticalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        AvailableRoomSearch.add(NaviBar);
        NaviBar.setBounds(0, 0, 852, 100);
        AvailableRoomSearch.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 850, 20);

        jPanel2.setMinimumSize(new java.awt.Dimension(852, 80));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 31, 61));
        jLabel2.setText(" Available Room Search");

        Wel.setText("Welcome ,");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(Wel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Wel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        AvailableRoomSearch.add(jPanel2);
        jPanel2.setBounds(0, 100, 852, 80);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 31, 61));
        jLabel1.setText("Room Type :");
        AvailableRoomSearch.add(jLabel1);
        jLabel1.setBounds(50, 200, 110, 40);

        RoomType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select --", "Superior Single Room", "Twin Sharing Room" }));
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeActionPerformed(evt);
            }
        });
        AvailableRoomSearch.add(RoomType);
        RoomType.setBounds(50, 240, 160, 30);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 31, 61));
        jLabel3.setText("Gender :");
        AvailableRoomSearch.add(jLabel3);
        jLabel3.setBounds(50, 300, 80, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Room Type", "Gender", "Status", "Occupancy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(74, 31, 61));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        AvailableRoomSearch.add(jScrollPane1);
        jScrollPane1.setBounds(250, 220, 570, 260);

        BookNow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BookNow.setText("Book Now");
        BookNow.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                BookNowMouseWheelMoved(evt);
            }
        });
        BookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNowActionPerformed(evt);
            }
        });
        AvailableRoomSearch.add(BookNow);
        BookNow.setBounds(60, 460, 140, 27);

        gender.add(Female);
        Female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        AvailableRoomSearch.add(Female);
        Female.setBounds(50, 370, 98, 25);

        gender.add(Male);
        Male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Male.setText("Male\n");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        AvailableRoomSearch.add(Male);
        Male.setBounds(50, 340, 98, 25);

        Check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Check.setText("Check Availability");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        AvailableRoomSearch.add(Check);
        Check.setBounds(60, 420, 140, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AvailableRoomSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AvailableRoomSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MyApplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyApplicationMouseClicked
        
        // TODO add your handling code here:
        MyApplication myapp = new MyApplication(Username.getText());
        
        myapp.Username.setText(Username.getText());
        myapp.setVisible(true);
        dispose();
    }//GEN-LAST:event_MyApplicationMouseClicked

    private void AvailableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableRoomMouseClicked
        // TODO add your handling code here:
        String uname = null;
        AvailableRoom ar = new AvailableRoom(uname);
        ar.Username.setText(Username.getText());
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_AvailableRoomMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        String uname = null;
        Booking book = new Booking(uname);
        book.Username.setText(Username.getText());
//        book.sid.setText(Username.getText());
        book.setVisible(true);
        dispose();
    }//GEN-LAST:event_BookingMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
        // TODO add your handling code here:
        String username = null;
        Payment payment = new Payment(username);
        payment.Username.setText(Username.getText());
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_PaymentMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                WelcomePage wp = new WelcomePage();
                wp.setVisible(true);
                dispose();
            } else {
                JOptionPane.getRootFrame().dispose();
            }
    }//GEN-LAST:event_LogoutMouseClicked

    private void RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTypeActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        // TODO add your handling code here:
        String option = RoomType.getSelectedItem().toString();
        if(!Male.isSelected()&&!Female.isSelected()){
                JOptionPane.showMessageDialog(null, "Please select gender.");
            }else if(option.equals("-- select --")){
                JOptionPane.showMessageDialog(null,"Please select a room type.");
            }     
            else{
                try (BufferedReader reader = new BufferedReader(new FileReader("AvailableRoom.txt"))) {         
            
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                       Object[] lines = reader.lines().toArray();
                       
                       dtm.setRowCount(0);
                       for(int i=0;i<lines.length;i++) {
                           String[] parts = lines[i].toString().split(">");
                           String roomnumber = parts[0] ;
                           String roomtype = parts[1] ;
                           String gender = parts[2] ;
                           String occupancy = parts[3] ;
                           String status = parts[4] ;
                           
                           if(Male.isSelected() && gender.equals("Male")){
                               if(option.equals("Superior Single Room")&&roomtype.equals("Superior Single Room")){
                               dtm.addRow(parts);
                               }else if(option.equals("Twin Sharing Room")&&roomtype.equals("Twin Sharing Room")){
                               dtm.addRow(parts);
                               }
                           }else if(Female.isSelected() && gender.equals("Female")){
                               if(option.equals("Superior Single Room")&&roomtype.equals("Superior Single Room")){
                               dtm.addRow(parts);
                               }else if(option.equals("Twin Sharing Room")&&roomtype.equals("Twin Sharing Room")){
                               dtm.addRow(parts);
                               }
                           }

                       }
                } catch (IOException e) {
                   JOptionPane.showMessageDialog(null, "Error");
                }
                }
   
    }//GEN-LAST:event_CheckActionPerformed

    private void BookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNowActionPerformed
        // TODO add your handling code here:
        String uname = null;
        Booking book = new Booking(uname);
        book.Username.setText(Username.getText());
        book.setVisible(true);
        dispose();
 
    }//GEN-LAST:event_BookNowActionPerformed

    private void BookNowMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_BookNowMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNowMouseWheelMoved

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableRoomSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableRoomSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableRoomSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableRoomSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String uname=null;
                new AvailableRoomSearch(uname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailableRoom;
    private javax.swing.JPanel AvailableRoomSearch;
    private javax.swing.JButton BookNow;
    private javax.swing.JLabel Booking;
    private javax.swing.JButton Check;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel MyApplication;
    private javax.swing.JPanel NaviBar;
    private javax.swing.JLabel Payment;
    private javax.swing.JComboBox<String> RoomType;
    public javax.swing.JLabel Username;
    private javax.swing.JLabel Wednesday;
    public javax.swing.JLabel Wel;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
