/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Dayna
 */
public class AvailableRoom extends javax.swing.JFrame {
    


    /**
     * Creates new form AvailableRoom
     * @param uname
     */
    public AvailableRoom(String uname) {
        initComponents();
        MyApplication ma = new MyApplication(uname);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        AvaulableRoom = new javax.swing.JPanel();
        NaviBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Wednesday = new javax.swing.JLabel();
        MyApplication = new javax.swing.JLabel();
        AvailableRoom = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Wel = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Availability1 = new javax.swing.JLabel();
        Availability2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jSeparator2.setBackground(new java.awt.Color(150, 150, 150));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AvaulableRoom.setBackground(new java.awt.Color(255, 255, 255));
        AvaulableRoom.setPreferredSize(new java.awt.Dimension(852, 550));
        AvaulableRoom.setLayout(null);

        NaviBar.setBackground(new java.awt.Color(74, 31, 61));
        NaviBar.setMinimumSize(new java.awt.Dimension(852, 80));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });

        Wednesday.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        Wednesday.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday.setText("WEDNESDAY");

        MyApplication.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        MyApplication.setForeground(new java.awt.Color(255, 255, 255));
        MyApplication.setText("My Application");
        MyApplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MyApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyApplicationMouseClicked(evt);
            }
        });

        AvailableRoom.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        AvailableRoom.setForeground(new java.awt.Color(255, 255, 255));
        AvailableRoom.setText("Available Room");
        AvailableRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvailableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableRoomMouseClicked(evt);
            }
        });

        Booking.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Booking.setForeground(new java.awt.Color(255, 255, 255));
        Booking.setText("Booking");
        Booking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Payment.setForeground(new java.awt.Color(255, 255, 255));
        Payment.setText("Payment");
        Payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NaviBarLayout = new javax.swing.GroupLayout(NaviBar);
        NaviBar.setLayout(NaviBarLayout);
        NaviBarLayout.setHorizontalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Wednesday))
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NaviBarLayout.setVerticalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MyApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        AvaulableRoom.add(NaviBar);
        NaviBar.setBounds(0, 0, 852, 100);
        AvaulableRoom.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 850, 10);

        jPanel2.setMinimumSize(new java.awt.Dimension(852, 80));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 31, 61));
        jLabel2.setText(" Available Room");

        Wel.setText("Welcome ,");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(Wel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        AvaulableRoom.add(jPanel2);
        jPanel2.setBounds(0, 100, 852, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/TwinSharing.png"))); // NOI18N
        AvaulableRoom.add(jLabel1);
        jLabel1.setBounds(560, 340, 250, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SuperiorSingle.png"))); // NOI18N
        AvaulableRoom.add(jLabel3);
        jLabel3.setBounds(40, 200, 250, 128);

        Availability1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Availability1.setForeground(new java.awt.Color(74, 31, 61));
        Availability1.setText("  Availability");
        Availability1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Availability1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Availability1MouseClicked(evt);
            }
        });
        AvaulableRoom.add(Availability1);
        Availability1.setBounds(200, 340, 90, 20);

        Availability2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Availability2.setForeground(new java.awt.Color(74, 31, 61));
        Availability2.setText(" Availability");
        Availability2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        AvaulableRoom.add(Availability2);
        Availability2.setBounds(710, 490, 100, 20);

        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        AvaulableRoom.add(jLabel8);
        jLabel8.setBounds(30, 190, 270, 180);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(74, 31, 61));
        jTextArea2.setRows(5);
        jTextArea2.setText("Fully furnished room, fully air-conditioned room (manually controlled), single bed, \nbed linens provided (pillow, bed sheet & comforter), rental charge is inclusive of \npublic utilities (water and electricity consumption), exclusive bathroom with hot \nand cold shower, daily housekeeping service, inclusive of laundry service, individual \nstudy desk with study light and personal safe box.");
        jTextArea2.setBorder(null);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AvaulableRoom.add(jTextArea2);
        jTextArea2.setBounds(30, 420, 500, 90);

        jLabel5.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel5.setText(" Twin Sharing Room");
        AvaulableRoom.add(jLabel5);
        jLabel5.setBounds(560, 480, 180, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(74, 31, 61));
        jLabel11.setText("Price : RM 1,000/mth (per person)");
        AvaulableRoom.add(jLabel11);
        jLabel11.setBounds(260, 390, 250, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(74, 31, 61));
        jLabel10.setText("Occupancy : 2");
        AvaulableRoom.add(jLabel10);
        jLabel10.setBounds(70, 390, 120, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(74, 31, 61));
        jLabel9.setText("Price : RM 1,500/mth");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AvaulableRoom.add(jLabel9);
        jLabel9.setBounds(560, 200, 150, 20);

        jLabel6.setFont(new java.awt.Font("Forte", 0, 16)); // NOI18N
        jLabel6.setText(" Superior Single Room");
        AvaulableRoom.add(jLabel6);
        jLabel6.setBounds(40, 330, 180, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 31, 61));
        jLabel4.setText("Occupancy : 1");
        AvaulableRoom.add(jLabel4);
        jLabel4.setBounds(380, 200, 120, 20);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(74, 31, 61));
        jTextArea3.setRows(5);
        jTextArea3.setText("Fully furnished room, fully air-conditioned room (manually controlled), single bed, \nbed linens provided (pillow, bed sheet & comforter), rental charge is inclusive of \npublic utilities (water and electricity consumption), exclusive bathroom with hot \nand cold shower, daily housekeeping service, inclusive of laundry service, \nindividual study desk with study light and personal safe box.");
        jTextArea3.setBorder(null);
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AvaulableRoom.add(jTextArea3);
        jTextArea3.setBounds(330, 230, 490, 90);

        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        AvaulableRoom.add(jLabel7);
        jLabel7.setBounds(550, 330, 270, 190);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Price.png"))); // NOI18N
        AvaulableRoom.add(jLabel13);
        jLabel13.setBounds(225, 385, 30, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Occupancy.png"))); // NOI18N
        AvaulableRoom.add(jLabel14);
        jLabel14.setBounds(30, 380, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Occupancy.png"))); // NOI18N
        AvaulableRoom.add(jLabel15);
        jLabel15.setBounds(343, 192, 30, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Price.png"))); // NOI18N
        AvaulableRoom.add(jLabel16);
        jLabel16.setBounds(510, 195, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AvaulableRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AvaulableRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableRoomMouseClicked
        // TODO add your handling code here:
        String uname = null;
        AvailableRoom ar = new AvailableRoom(uname);
        ar.Username.setText(Username.getText());
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_AvailableRoomMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        String uname = null;
        Booking book = new Booking(uname);
        book.Username.setText(Username.getText());
//        book.sid.setText(Username.getText());
        book.setVisible(true);
        dispose();
    }//GEN-LAST:event_BookingMouseClicked

    private void MyApplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyApplicationMouseClicked
        
        // TODO add your handling code here:
        MyApplication myapp = new MyApplication(Username.getText());
        myapp.Username.setText(Username.getText());
        myapp.setVisible(true);
        dispose();
    }//GEN-LAST:event_MyApplicationMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
        // TODO add your handling code here:
        String username = null;
        Payment payment = new Payment(username);
        payment.Username.setText(Username.getText());
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_PaymentMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                WelcomePage wp = new WelcomePage();
                wp.setVisible(true);
                dispose();
            } else {
                JOptionPane.getRootFrame().dispose();
            }
    }//GEN-LAST:event_LogoutMouseClicked

    private void Availability1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Availability1MouseClicked
        // TODO add your handling code here
        String username = null;
        AvailableRoomSearch av = new AvailableRoomSearch(username);
        av.Username.setText(Username.getText());
        av.setVisible(true);
        dispose();
    }//GEN-LAST:event_Availability1MouseClicked

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String uname = null;
                new AvailableRoom(uname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Availability1;
    private javax.swing.JLabel Availability2;
    private javax.swing.JLabel AvailableRoom;
    private javax.swing.JPanel AvaulableRoom;
    private javax.swing.JLabel Booking;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout;
    public javax.swing.JLabel MyApplication;
    private javax.swing.JPanel NaviBar;
    private javax.swing.JLabel Payment;
    public javax.swing.JLabel Username;
    private javax.swing.JLabel Wednesday;
    public javax.swing.JLabel Wel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
