/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Code.deleteInfo;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author waiho
 */
public class DeleteInfo extends javax.swing.JFrame {

    /**
     * Creates new form DeleteInfo
     */
    public DeleteInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteInfo = new javax.swing.JPanel();
        NaviBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Wednesday = new javax.swing.JLabel();
        ManageInfo = new javax.swing.JLabel();
        ManageApplication = new javax.swing.JLabel();
        CheckRecord = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        HostelInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeleteInfoTable = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        roomno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeleteInfo.setBackground(new java.awt.Color(74, 31, 61));
        DeleteInfo.setPreferredSize(new java.awt.Dimension(852, 550));
        DeleteInfo.setLayout(null);

        NaviBar.setBackground(new java.awt.Color(74, 31, 61));
        NaviBar.setMinimumSize(new java.awt.Dimension(852, 80));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N

        Wednesday.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        Wednesday.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday.setText("WEDNESDAY");

        ManageInfo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        ManageInfo.setForeground(new java.awt.Color(255, 255, 255));
        ManageInfo.setText("Manage Info");
        ManageInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageInfoMouseClicked(evt);
            }
        });

        ManageApplication.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        ManageApplication.setForeground(new java.awt.Color(255, 255, 255));
        ManageApplication.setText("Manage Application");
        ManageApplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageApplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageApplicationMouseClicked(evt);
            }
        });

        CheckRecord.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        CheckRecord.setForeground(new java.awt.Color(255, 255, 255));
        CheckRecord.setText("Check Record");
        CheckRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckRecordMouseClicked(evt);
            }
        });

        Report.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Report.setForeground(new java.awt.Color(255, 255, 255));
        Report.setText("Report");
        Report.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NaviBarLayout = new javax.swing.GroupLayout(NaviBar);
        NaviBar.setLayout(NaviBarLayout);
        NaviBarLayout.setHorizontalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Wednesday))
                    .addGroup(NaviBarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(ManageApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageInfo)
                .addGap(18, 18, 18)
                .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NaviBarLayout.setVerticalGroup(
            NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NaviBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ManageInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CheckRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        DeleteInfo.add(NaviBar);
        NaviBar.setBounds(0, 0, 852, 100);
        DeleteInfo.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 850, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(852, 80));

        HostelInfo.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        HostelInfo.setForeground(new java.awt.Color(74, 31, 61));
        HostelInfo.setText("Hostel Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(HostelInfo)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(HostelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        DeleteInfo.add(jPanel2);
        jPanel2.setBounds(0, 100, 852, 80);

        DeleteInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Room Type", "Gender", "Status", "Occupancy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DeleteInfoTable);

        DeleteInfo.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 800, 200);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        DeleteInfo.add(Search);
        Search.setBounds(720, 210, 100, 23);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        DeleteInfo.add(Delete);
        Delete.setBounds(290, 470, 110, 30);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        DeleteInfo.add(Back);
        Back.setBounds(470, 470, 110, 30);

        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });
        DeleteInfo.add(roomno);
        roomno.setBounds(550, 210, 160, 22);

        jLabel1.setText("Room No. :");
        DeleteInfo.add(jLabel1);
        jLabel1.setBounds(480, 210, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeleteInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeleteInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageInfoMouseClicked
        // TODO add your handling code here:
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageInfoMouseClicked

    private void ManageApplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageApplicationMouseClicked
        // TODO add your handling code here:
        ManageApplication ma = new ManageApplication();
        ma.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageApplicationMouseClicked

    private void CheckRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckRecordMouseClicked
        // TODO add your handling code here:
        CheckRecord cr = new CheckRecord();
        cr.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckRecordMouseClicked

    private void ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseClicked
        // TODO add your handling code here:
        Report r = new Report();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReportMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                WelcomePage wp = new WelcomePage();
                wp.setVisible(true);
                dispose();
            } else {
                JOptionPane.getRootFrame().dispose();
            }
    }//GEN-LAST:event_LogoutMouseClicked

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String room = roomno.getText();
        deleteInfo d = new deleteInfo(room);        
    }//GEN-LAST:event_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:    
        try {
            DefaultTableModel dtm = (DefaultTableModel) DeleteInfoTable.getModel();
            dtm.setRowCount(0);
            boolean applicationFound = false;
            String room = roomno.getText();
                    try (BufferedReader reader = new BufferedReader(new FileReader("AvailableRoom.txt"))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            String[] parts = line.split(">");
                            String rn = parts[0];                        
                        if (room.equals(rn)) {
                            dtm.addRow(parts);
                            applicationFound = true;
                            break;
                        }
                        else if(!room.equals(rn)){
                            applicationFound = false;
                        }
                        }
                    }                    
                    
                    if (applicationFound==false) {
                        JOptionPane.showMessageDialog(null, "Room number not found.");
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(ManageApplication.class.getName()).log(Level.SEVERE, null, ex);
                }       
        
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel CheckRecord;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel DeleteInfo;
    private javax.swing.JTable DeleteInfoTable;
    private javax.swing.JLabel HostelInfo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel ManageApplication;
    private javax.swing.JLabel ManageInfo;
    private javax.swing.JPanel NaviBar;
    private javax.swing.JLabel Report;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Wednesday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField roomno;
    // End of variables declaration//GEN-END:variables
}
