/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dayna
 */
public class MyApplication extends javax.swing.JFrame {

    /**
     * Creates new form MyApplication
     * @param uname
     */
    public MyApplication(String uname) {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MyApplication = new javax.swing.JPanel();
        NaviBar4 = new javax.swing.JPanel();
        Logo4 = new javax.swing.JLabel();
        Wednesday4 = new javax.swing.JLabel();
        Myapplication = new javax.swing.JLabel();
        AvailableRoom = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Wel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        norecord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        History = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Status = new javax.swing.JLabel();
        roomtype = new javax.swing.JLabel();
        Adate = new javax.swing.JLabel();
        Cdate = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        Show = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MyApplication.setBackground(new java.awt.Color(255, 255, 255));
        MyApplication.setPreferredSize(new java.awt.Dimension(852, 550));
        MyApplication.setLayout(null);

        NaviBar4.setBackground(new java.awt.Color(74, 31, 61));
        NaviBar4.setMinimumSize(new java.awt.Dimension(852, 80));

        Logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon logo.png"))); // NOI18N
        Logo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logo4MouseClicked(evt);
            }
        });

        Wednesday4.setBackground(new java.awt.Color(255, 255, 255));
        Wednesday4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        Wednesday4.setForeground(new java.awt.Color(255, 255, 255));
        Wednesday4.setText("WEDNESDAY");

        Myapplication.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Myapplication.setForeground(new java.awt.Color(255, 255, 255));
        Myapplication.setText("My Application");
        Myapplication.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Myapplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyapplicationMouseClicked(evt);
            }
        });

        AvailableRoom.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        AvailableRoom.setForeground(new java.awt.Color(255, 255, 255));
        AvailableRoom.setText("Available Room");
        AvailableRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AvailableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableRoomMouseClicked(evt);
            }
        });

        Booking.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Booking.setForeground(new java.awt.Color(255, 255, 255));
        Booking.setText("Booking");
        Booking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Payment.setForeground(new java.awt.Color(255, 255, 255));
        Payment.setText("Payment");
        Payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NaviBar4Layout = new javax.swing.GroupLayout(NaviBar4);
        NaviBar4.setLayout(NaviBar4Layout);
        NaviBar4Layout.setHorizontalGroup(
            NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBar4Layout.createSequentialGroup()
                .addGroup(NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NaviBar4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Wednesday4))
                    .addGroup(NaviBar4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Logo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Myapplication, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NaviBar4Layout.setVerticalGroup(
            NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaviBar4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NaviBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Myapplication, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        MyApplication.add(NaviBar4);
        NaviBar4.setBounds(0, 0, 852, 100);
        MyApplication.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 850, 20);

        jPanel6.setMinimumSize(new java.awt.Dimension(852, 80));

        jLabel16.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(74, 31, 61));
        jLabel16.setText("My Application");

        Wel.setText("Welcome ,");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(175, 175, 175)
                .addComponent(Wel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Wel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        MyApplication.add(jPanel6);
        jPanel6.setBounds(0, 100, 852, 80);

        jLabel17.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(74, 31, 61));
        jLabel17.setText("History");
        MyApplication.add(jLabel17);
        jLabel17.setBounds(20, 360, 90, 30);

        jLabel18.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(74, 31, 61));
        jLabel18.setText("Recent");
        MyApplication.add(jLabel18);
        jLabel18.setBounds(20, 190, 90, 30);

        norecord.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                norecordPropertyChange(evt);
            }
        });
        MyApplication.add(norecord);
        norecord.setBounds(20, 226, 240, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/down arrow.png"))); // NOI18N
        MyApplication.add(jLabel2);
        jLabel2.setBounds(120, 360, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/down arrow.png"))); // NOI18N
        MyApplication.add(jLabel3);
        jLabel3.setBounds(110, 190, 30, 30);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 31, 61));
        jLabel4.setText("Status :");
        MyApplication.add(jLabel4);
        jLabel4.setBounds(440, 310, 110, 30);

        History.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Application ID", "Student ID", "Full Name", "Gender", "Room Type", "Arrival Date", "Check Out Date", "Status", "Payment", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(History);

        MyApplication.add(jScrollPane2);
        jScrollPane2.setBounds(0, 400, 850, 130);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(74, 31, 61));
        jLabel5.setText("Room Type :");
        MyApplication.add(jLabel5);
        jLabel5.setBounds(60, 230, 120, 30);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 31, 61));
        jLabel6.setText("Arrival Date :");
        MyApplication.add(jLabel6);
        jLabel6.setBounds(60, 270, 120, 30);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(74, 31, 61));
        jLabel7.setText("Check Out Date :");
        MyApplication.add(jLabel7);
        jLabel7.setBounds(60, 310, 140, 30);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(74, 31, 61));
        jLabel8.setText("Student ID :");
        MyApplication.add(jLabel8);
        jLabel8.setBounds(440, 230, 110, 30);

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(74, 31, 61));
        jLabel9.setText("Gender :");
        MyApplication.add(jLabel9);
        jLabel9.setBounds(440, 270, 110, 30);
        MyApplication.add(jSeparator2);
        jSeparator2.setBounds(30, 350, 790, 10);
        MyApplication.add(Status);
        Status.setBounds(520, 310, 240, 30);
        MyApplication.add(roomtype);
        roomtype.setBounds(160, 230, 230, 30);
        MyApplication.add(Adate);
        Adate.setBounds(160, 270, 250, 30);
        MyApplication.add(Cdate);
        Cdate.setBounds(180, 310, 230, 30);
        MyApplication.add(StudentID);
        StudentID.setBounds(530, 230, 250, 30);
        MyApplication.add(gender);
        gender.setBounds(530, 270, 220, 30);

        Show.setText("Search");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        MyApplication.add(Show);
        Show.setBounds(690, 310, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableRoomMouseClicked
        // TODO add your handling code here:
        String uname = null;
        AvailableRoom ar = new AvailableRoom(uname);
        ar.Username.setText(Username.getText());
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_AvailableRoomMouseClicked

    private void MyapplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyapplicationMouseClicked
        // TODO add your handling code here:
        MyApplication myapp = new MyApplication(Username.getText());
        myapp.StudentID.setText(Username.getText());
        myapp.Username.setText(Username.getText());
        myapp.setVisible(true);
        dispose();
    }//GEN-LAST:event_MyapplicationMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        String uname=null;
        Booking book = new Booking(uname);
        book.Username.setText(Username.getText());
//        book.sid.setText(Username.getText());
        book.setVisible(true);
        dispose();
    }//GEN-LAST:event_BookingMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
        // TODO add your handling code here:
        String username = null;
        Payment payment = new Payment(username);
        payment.Username.setText(Username.getText());
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_PaymentMouseClicked

    private void Logo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logo4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Logo4MouseClicked

    private void norecordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_norecordPropertyChange
        // TODO add your handling code here:
 
    }//GEN-LAST:event_norecordPropertyChange

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.YES_OPTION) {
                WelcomePage wp = new WelcomePage();
                wp.setVisible(true);
                dispose();
            } else {
                JOptionPane.getRootFrame().dispose();
            }
    }//GEN-LAST:event_LogoutMouseClicked

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        String U = Username.getText();
        boolean add = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("Application.txt"))) {
            String line;
            
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(">");
                String A = parts[0];
                String tp = parts[1];
                String fn = parts[2];
                String g = parts[3];
                String rt = parts[4];
                String ad = parts[5];
                String cd = parts[6];
                String s = parts[7];
                

                if (U.equals(tp)&&s.equals("Pending")) {
                    
                    roomtype.setText(rt);
                    gender.setText(g);
                    Status.setText(s);
                    Adate.setText(ad);
                    Cdate.setText(cd);
                    StudentID.setText(tp);
                    add = true;
                    break;

                } else {
                    add = false;
                    // Create a new line with the updated information and add it to updatedLines
                    roomtype.setText("-");
                    gender.setText("-");
                    Status.setText("-");
                    Adate.setText("-");
                    Cdate.setText("-");
                    StudentID.setText("-");
                }
            }
            if (add!=false){
                JOptionPane.showMessageDialog(null, "Application found.");
            }else{
                JOptionPane.showMessageDialog(null, "No rencent application");
            }
        }   catch (FileNotFoundException ex) {
            Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try (BufferedReader reader = new BufferedReader(new FileReader("Application.txt"))) {         
            
                    DefaultTableModel dtm = (DefaultTableModel) History.getModel();
                       Object[] lines = reader.lines().toArray();
                       boolean add1=false;
                       dtm.setRowCount(0);
                       for(int i=0;i<lines.length;i++) {
                           String[] parts = lines[i].toString().split(">");
                            String tp = parts[1];
                            String s = parts[7];
                           
                           if(!s.equals("Pending")&&U.equals(tp)){
                               dtm.addRow(parts);
                               add1=true;
                               }
                        }
                       if(add1==true){
                               JOptionPane.showMessageDialog(null,"Previuos application found.");
                           }else{
                               JOptionPane.showMessageDialog(null,"No previous application.");
                           }
                } catch (IOException e) {
                   JOptionPane.showMessageDialog(null, "Error");
                }
    }//GEN-LAST:event_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String uname = null;
                new MyApplication(uname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adate;
    private javax.swing.JLabel AvailableRoom;
    private javax.swing.JLabel Booking;
    private javax.swing.JLabel Cdate;
    private javax.swing.JTable History;
    private javax.swing.JLabel Logo4;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MyApplication;
    private javax.swing.JLabel Myapplication;
    private javax.swing.JPanel NaviBar4;
    private javax.swing.JLabel Payment;
    private javax.swing.JButton Show;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel StudentID;
    public javax.swing.JLabel Username;
    private javax.swing.JLabel Wednesday4;
    public javax.swing.JLabel Wel;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel norecord;
    private javax.swing.JLabel roomtype;
    // End of variables declaration//GEN-END:variables
}

